name: libmobility-examples
channels:
  - conda-forge
  - stochasticHydroTools
  - nodefaults
dependencies:
  - python
#  - cuda-version==12.9 # Uncomment if your GPU needs a specific CUDA version
  - libMobility<2
  - numpy
  - cupy
  - scipy
  - spreadinterp<2
  - pandas<3
  - matplotlib<4
  - cmap
  - numba
  - pyvista
  - pyamg
  # Rigid dependencies below
  - nanobind
  - cxx-compiler
  - eigen
  - pip
  - pip:
    - ./rheology_shear/deps/Rigid_Body_Light
    # - plotoptix # uncomment if you want to run the optix.py plotting code in the shear example
  - tbb
  - tqdm
  - scipy<=1.15

